  name: Calculate Carbon
  
  on: workflow_dispatch
        
  jobs:
    carbon-measure:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version: 1.17
        - name: Set and check goenv
          run: |
              go env -w GO111MODULE=on
              go version && go env
        - id: carbon_output
          uses: ./src/test
          
          
        
    

